/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author fatiq
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private final String url = "jdbc:postgresql://localhost:5432/PBO";
    private final String user = "postgres";
    private final String pass = "5127";
    private Connection conn = null;
    
    public Main() throws SQLException {
        initComponents();
        conn = DriverManager.getConnection(url,user,pass);
        tampilkan();
        setColWidht();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_isi = new javax.swing.JTable();
        btn_cetak = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JPanel();
        lb_tambah = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_batal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("STSong", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Santri");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 60));

        tbl_isi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAMA", "JK", "ALAMAT", "USIA", "TLP"
            }
        ));
        tbl_isi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_isiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_isi);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 950, 420));

        btn_cetak.setBackground(new java.awt.Color(0, 204, 51));
        btn_cetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cetakMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CETAK");

        javax.swing.GroupLayout btn_cetakLayout = new javax.swing.GroupLayout(btn_cetak);
        btn_cetak.setLayout(btn_cetakLayout);
        btn_cetakLayout.setHorizontalGroup(
            btn_cetakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(btn_cetakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        btn_cetakLayout.setVerticalGroup(
            btn_cetakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
            .addGroup(btn_cetakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_cetakLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel1.add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, -1, 30));

        btn_tambah.setBackground(new java.awt.Color(0, 0, 255));
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });

        lb_tambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_tambah.setForeground(new java.awt.Color(255, 255, 255));
        lb_tambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tambah.setText("TAMBAH");

        javax.swing.GroupLayout btn_tambahLayout = new javax.swing.GroupLayout(btn_tambah);
        btn_tambah.setLayout(btn_tambahLayout);
        btn_tambahLayout.setHorizontalGroup(
            btn_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_tambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btn_tambahLayout.setVerticalGroup(
            btn_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_tambahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, -1, 30));

        btn_hapus.setBackground(new java.awt.Color(255, 0, 0));
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HAPUS");

        javax.swing.GroupLayout btn_hapusLayout = new javax.swing.GroupLayout(btn_hapus);
        btn_hapus.setLayout(btn_hapusLayout);
        btn_hapusLayout.setHorizontalGroup(
            btn_hapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(btn_hapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        btn_hapusLayout.setVerticalGroup(
            btn_hapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
            .addGroup(btn_hapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_hapusLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, -1, 30));

        btn_batal.setBackground(new java.awt.Color(0, 0, 0));
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BATAL");

        javax.swing.GroupLayout btn_batalLayout = new javax.swing.GroupLayout(btn_batal);
        btn_batal.setLayout(btn_batalLayout);
        btn_batalLayout.setHorizontalGroup(
            btn_batalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(btn_batalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
        );
        btn_batalLayout.setVerticalGroup(
            btn_batalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
            .addGroup(btn_batalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_batalLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel1.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        try {
            if(lb_tambah.getText().equalsIgnoreCase("TAMBAH")){
                new Tambah(null,true).setVisible(true);
            } else {
                int index = tbl_isi.getSelectedRow();
                Santri sn = new Santri();
                sn.setId((String) tbl_isi.getValueAt(index, 0));
                sn.setNama((String) tbl_isi.getValueAt(index, 1));
                sn.setJk((String) tbl_isi.getValueAt(index, 2));
                sn.setAlamat((String) tbl_isi.getValueAt(index, 3));
                sn.setUsia((int) tbl_isi.getValueAt(index, 4));
                sn.setTlp((String) tbl_isi.getValueAt(index, 5));
                new Tambah(null,true,sn).setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        tampilkan();
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        hapus((String) tbl_isi.getValueAt(tbl_isi.getSelectedRow(), 0));                           
        tampilkan();
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_cetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseClicked
        try{
            Date tgl = new Date();
            String reportPath = "src/latihan/cetak.jasper";

            HashMap<String, Object> parameters = new HashMap<>();
            parameters.put("tgl",tgl);
            
            JasperPrint print = JasperFillManager.fillReport(reportPath,parameters,conn);
            JasperViewer viewer = new JasperViewer(print,false);
            viewer.setVisible(true); 
        } catch (JRException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_cetakMouseClicked

    private void tbl_isiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_isiMouseClicked
        btn_hapus.setVisible(true);
        btn_batal.setVisible(true);
        if(lb_tambah.getText().equals("TAMBAH")){
            lb_tambah.setText("UBAH");
        }
    }//GEN-LAST:event_tbl_isiMouseClicked

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        tampilkan();
    }//GEN-LAST:event_btn_batalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_batal;
    private javax.swing.JPanel btn_cetak;
    private javax.swing.JPanel btn_hapus;
    private javax.swing.JPanel btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_tambah;
    private javax.swing.JTable tbl_isi;
    // End of variables declaration//GEN-END:variables

    private void tampilkan(){
        PreparedStatement st = null;
        ArrayList<Santri> list = new ArrayList();
        ResultSet rs = null;
        String query = "SELECT * FROM santri ";
        try{
            st = conn.prepareStatement(query);
            rs = st.executeQuery();
            while(rs.next()){
                Santri sn = new Santri();
                
                sn.setId(rs.getString("id_santri"));
                sn.setNama(rs.getString("nama"));
                sn.setJk(rs.getString("jenis_kelamin"));
                sn.setAlamat(rs.getString("alamat"));
                sn.setTlp(rs.getString("no_tlp"));
                sn.setUsia(Integer.parseInt(rs.getString("usia")));
                
                list.add(sn);
            }
            
            DefaultTableModel tbl = (DefaultTableModel) tbl_isi.getModel();
            tbl.setRowCount(0);
            int i = 1;
            for(Santri data : list){
                Object[] baris = new Object[6];
                
                baris[0] = data.getId();
                baris[1] = data.getNama();
                baris[2] = data.getJk();
                baris[3] = data.getAlamat();
                baris[4] = data.getUsia();
                baris[5] = data.getTlp();
                
                tbl.addRow(baris);
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
        btn_hapus.setVisible(false);
        btn_batal.setVisible(false);
        if(lb_tambah.getText().equals("UBAH")){
            lb_tambah.setText("TAMBAH");
        }
    }
    
    private void hapus(String id){
        String query = "DELETE FROM santri WHERE id_santri = ?";
        try{
            PreparedStatement stmt = null;
            stmt = conn.prepareStatement(query);
            
            stmt.setString(1, id);
              
            stmt.executeUpdate();
        } catch (SQLException e){
            e.printStackTrace();
        }
    }
    private void setColWidht() {
        int[] noCol = {0,1,2,4,5};
        int[] noColW = {40,200,30,40,150};
        
        TableColumnModel tblModel = tbl_isi.getColumnModel();
        for(int i = 0; i < noCol.length; i++){
        tblModel.getColumn(noCol[i]).setPreferredWidth(noColW[i]);
        tblModel.getColumn(noCol[i]).setMaxWidth(noColW[i]);
        tblModel.getColumn(noCol[i]).setMinWidth(noColW[i]);
        }
    }

}
